# Generated by Django 5.1.1 on 2024-10-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_profile_email_profile_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
