# Generated by Django 5.1.1 on 2024-10-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=100)),
                ('ear_tag', models.CharField(max_length=50, unique=True)),
                ('sire_id', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('weight_at_birth', models.FloatField()),
            ],
        ),
    ]
