# Generated by Django 5.1.1 on 2024-10-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('cow_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cow_name', models.CharField(max_length=100)),
                ('ear_tag', models.CharField(max_length=50, unique=True)),
                ('sire_id', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('weight_at_birth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_date', models.DateField()),
                ('cow_id', models.CharField(max_length=50)),
                ('cow_name', models.CharField(max_length=100)),
                ('morning_milk_quantity', models.FloatField()),
                ('afternoon_milk_quantity', models.FloatField()),
                ('evening_milk_quantity', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
