# Generated by Django 5.1.1 on 2024-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cow_milkrecord_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_name', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=15)),
                ('amount_bought', models.FloatField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='cow',
            name='animal_type',
            field=models.CharField(choices=[('COW', 'Cow'), ('CALF', 'Calf')], default='Cow', max_length=10),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='afternoon_milk_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='evening_milk_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='morning_milk_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
