# Generated by Django 5.1.1 on 2024-10-19 22:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_milksale_cow_animal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
