# Generated by Django 5.1.1 on 2024-10-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_milksale_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_date', models.DateField()),
                ('breeding_date', models.DateField()),
                ('bull_name', models.CharField(max_length=100)),
                ('bull_id', models.CharField(max_length=50)),
                ('cow_name', models.CharField(max_length=100)),
                ('pregnancy_diagnosis_date', models.DateField(blank=True, null=True)),
                ('date_due_to_calve', models.DateField(blank=True, null=True)),
                ('date_calved', models.DateField(blank=True, null=True)),
                ('age_of_cow_at_calving', models.PositiveIntegerField(blank=True, null=True)),
                ('calf_name', models.CharField(blank=True, max_length=100, null=True)),
                ('calf_id', models.CharField(blank=True, max_length=50, null=True)),
                ('calving_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
