# Generated by Django 5.1.1 on 2024-10-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_breeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incurred', models.DateField()),
                ('expense_type', models.CharField(choices=[('FEED', 'Feed'), ('VETERINARY', 'Veterinary'), ('EQUIPMENT', 'Equipment'), ('LABOR', 'Labor'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=20)),
                ('amount_incurred', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='breeding',
            name='heat_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
