# Generated by Django 5.1.1 on 2024-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFeed',
            fields=[
                ('feed_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('feed_type', models.CharField(choices=[('HAY', 'Hay'), ('SILAGE', 'Silage'), ('GRAINS', 'Grains'), ('CONCENTRATE', 'Concentrate')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
