# Generated by Django 5.1.1 on 2024-10-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_stockfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='heat_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_type',
            field=models.CharField(choices=[('HAY', 'Hay'), ('SILAGE', 'Silage'), ('NAPPIER', 'Nappier'), ('CONCENTRATE', 'Concentrate')], max_length=50),
        ),
    ]
