# Generated by Django 5.1.1 on 2024-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_breeding_heat_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FarmExpense',
            new_name='FarmFinance',
        ),
        migrations.AlterField(
            model_name='breeding',
            name='heat_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_type',
            field=models.CharField(choices=[('HAY', 'Hay'), ('SILAGE', 'Silage'), ('NAPPIER', 'Nappier'), ('DAIRY MEAL', 'Dairy Meal'), ('MAIZE BRAND', 'Maize Brand'), ('SALT SUPPLIMENTS', 'Salt suppliment')], max_length=50),
        ),
    ]
