# Generated by Django 5.1.1 on 2024-10-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_farmexpense_farmfinance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cow',
            name='weight_at_birth',
        ),
    ]
