# Generated by Django 5.1.1 on 2024-10-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_cow_weight_at_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cow',
            new_name='Animal',
        ),
    ]
