# Generated by Django 5.1.1 on 2024-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_cow_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='milking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
