# Generated by Django 5.1.1 on 2024-10-22 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_milkrecord_milking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_id',
            field=models.CharField(default='C001', max_length=50),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='milking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='milksale',
            name='current_date',
            field=models.DateField(),
        ),
    ]
