# Generated by Django 5.1.1 on 2024-10-22 21:14

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_milkrecord_cow_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ven', unique=True),
        ),
    ]
