# Generated by Django 5.1.1 on 2024-10-22 21:21

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_milkrecord_cow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='c', unique=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
