# Generated by Django 5.1.1 on 2024-10-23 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_milkrecord_cow_id_alter_milkrecord_cow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='date_incurred',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
        ),
    ]
