# Generated by Django 5.1.1 on 2024-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_farmfinance_date_incurred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('FEED', 'Feed'), ('VETERINARY', 'Veterinary'), ('EQUIPMENT', 'Equipment'), ('LABOR', 'Labor'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20, null=True),
        ),
    ]
