# Generated by Django 5.1.1 on 2024-10-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_farmfinance_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_id',
            field=models.CharField(max_length=20),
        ),
    ]
