# Generated by Django 5.1.1 on 2024-10-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_milkrecord_cow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='date_incurred',
            field=models.DateField(default=datetime.date(2024, 10, 24)),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
