# Generated by Django 5.1.1 on 2024-11-17 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_farmfinance_date_incurred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='date_incurred',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
