# Generated by Django 5.1.1 on 2024-11-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_farmfinance_date_incurred_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
    ]
