# Generated by Django 5.1.1 on 2024-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_employee_basic_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('Cow', 'Cow'), ('Calf', 'Calf')], default='Cow', max_length=10),
        ),
    ]
