# Generated by Django 5.1.1 on 2024-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_animal_animal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='expense_type',
            field=models.CharField(choices=[('FEED', 'Feed'), ('VETERINARY', 'Veterinary'), ('EQUIPMENT', 'Equipment'), ('LABOR', 'Labor'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
