# Generated by Django 5.1.1 on 2024-11-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_farmfinance_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmfinance',
            name='expense_type',
            field=models.CharField(choices=[('Feed', 'Feed'), ('Veterinary', 'Veterinary'), ('Equipment', 'Equipment'), ('Labor', 'Labor'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
    ]
