# Generated by Django 5.1.1 on 2024-11-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_farmfinance_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Farm_manager', 'Farm Manager'), ('Milker', 'Milker'), ('Herdsman', 'Herdsman')], default='Milker', max_length=20, null=True),
        ),
    ]
