# Generated by Django 5.1.1 on 2024-11-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Farm Manager', 'Farm Manager'), ('Milker', 'Milker'), ('Herdsman', 'Herdsman')], default='Milker', max_length=20, null=True),
        ),
    ]
