# Generated by Django 5.1.1 on 2024-11-21 20:19

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=5, max_length=20, prefix='SF', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_type',
            field=models.CharField(choices=[('Hay', 'Hay'), ('Silage', 'Silage'), ('Nappier', 'Nappier'), ('Dairy Meal', 'Dairy Meal'), ('Maize Brand', 'Maize Brand'), ('Salt suppliment', 'Salt suppliment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Kilogram(kg)', 'Kilogram(kg)'), ('gram(g)', 'gram(g)'), ('Litres(l)', 'Litres(l)')], max_length=15),
        ),
    ]
