# Generated by Django 5.1.1 on 2024-11-21 20:25

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_stockfeed_feed_id_alter_stockfeed_feed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='SF', primary_key=True, serialize=False, unique=True),
        ),
    ]
