# Generated by Django 5.1.1 on 2024-11-21 20:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_stockfeed_feed_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='sire_id',
        ),
        migrations.RemoveField(
            model_name='breeding',
            name='bull_id',
        ),
        migrations.RemoveField(
            model_name='breeding',
            name='id',
        ),
        migrations.RemoveField(
            model_name='milkrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='cow_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='c', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='calf_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='cf', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='cow_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='c', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='f', primary_key=True, serialize=False, unique=True),
        ),
    ]
