# Generated by Django 5.1.1 on 2024-11-21 21:01

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_animal_sire_id_remove_breeding_bull_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkrecord',
            name='cow_id',
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='record_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='r', primary_key=True, serialize=False, unique=True),
        ),
    ]
