# Generated by Django 5.1.1 on 2024-11-21 21:17

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_milkrecord_cow_id_milkrecord_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='record_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='R', primary_key=True, serialize=False, unique=True),
        ),
    ]
