# Generated by Django 5.1.1 on 2024-11-22 06:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_milkrecord_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfeed',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
