# Generated by Django 5.1.1 on 2024-11-23 08:57

import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_stockfeed_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockfeed',
            name='feed_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='F', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockfeed',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
    ]
