# Generated by Django 5.1.1 on 2024-11-24 13:05

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_stockfeed_feed_id_alter_stockfeed_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milksale',
            name='id',
        ),
        migrations.AddField(
            model_name='milksale',
            name='sale_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='S', primary_key=True, serialize=False, unique=True),
        ),
    ]
