# Generated by Django 5.1.1 on 2024-12-04 08:39

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_milksale_id_milksale_sale_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cow_id',
        ),
        migrations.AlterField(
            model_name='animal',
            name='ear_tag',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=3, max_length=20, prefix='c', primary_key=True, serialize=False, unique=True),
        ),
    ]
