# Generated by Django 5.1.1 on 2024-12-04 09:49

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_animal_cow_id_alter_animal_ear_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeding',
            name='calf_id',
        ),
        migrations.AddField(
            model_name='breeding',
            name='breeding_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=3, max_length=20, prefix='B', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ear_tag',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZO123456789', length=3, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
