# Generated by Django 5.1.1 on 2024-12-04 10:27

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_breeding_calf_id_breeding_breeding_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='breeding_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=20, prefix='B', primary_key=True, serialize=False, unique=True),
        ),
    ]
