# Generated by Django 5.1.1 on 2024-12-15 11:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_breeding_breeding_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='afternoon_milk_quantity',
            field=models.FloatField(blank=True, default=Decimal('0.00'), null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='evening_milk_quantity',
            field=models.FloatField(blank=True, default=Decimal('0.00'), null=True),
        ),
    ]
