# Generated by Django 5.1.1 on 2024-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_milkrecord_afternoon_milk_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkrecord',
            name='afternoon_milk_quantity',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='milkrecord',
            name='evening_milk_quantity',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
