# Generated by Django 5.1.1 on 2024-12-15 14:52

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_milkrecord_afternoon_milk_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmfinance',
            name='id',
        ),
        migrations.AddField(
            model_name='farmfinance',
            name='finance_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=3, max_length=20, prefix='F', primary_key=True, serialize=False, unique=True),
        ),
    ]
