# Generated by Django 5.1.1 on 2024-12-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_farmfinance_id_farmfinance_finance_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
    ]
