# Generated by Django 5.1.1 on 2024-12-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
